[package]
name = "family-photos"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25"
common = { version = "0.1.0", path = "../common" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
